name: Guix channel checks

on:
  push:
  workflow_dispatch:

jobs:
  channel:
    runs-on: codeberg-medium
    steps:
      - name: Check out repository
        uses: https://data.forgejo.org/actions/checkout@v4

      - name: Install Guix
        uses: https://github.com/PromyLOPh/guix-install-action@v1.6
        with:
          channels: |-
            (list (channel
                   (name 'guix)
                   (url "https://codeberg.org/guix/guix.git")
                   (branch "master")
                   (commit "1cb710f1fba398c69f4bb4aed0f88ca0b56af56a")
                   (introduction
                    (make-channel-introduction
                     "9edb3f66fd807b096b48283debdcddccfea34bad"
                     (openpgp-fingerprint
                      "BBB0 2DDF 2CEA F6A8 0D1D  E643 A2A0 6DF2 A33A 54FA"))))
                  (channel
                   (name 'nonguix)
                   (url "https://gitlab.com/nonguix/nonguix")
                   (branch "master")
                   (commit "0107c1c4849460b567424ba2cdc8942294c7a611")
                   (introduction
                    (make-channel-introduction
                     "897c1a470da759236cc11798f4e0a5f7d4d59fbc"
                     (openpgp-fingerprint
                      "2A39 3FFF 68F4 EF7A 3D29  12AF 6F51 20A0 22FB B2D5")))))

      - name: Show Guix version
        run: guix --version

      - name: Check Guix channel packages
        run: bash ./scripts/check-channel-packages --all
